#!/usr/bin/env bash
#
# @license BSD-3-Clause
#
# Copyright (c) 2019 Project Jupyter Contributors.
# Distributed under the terms of the 3-Clause BSD License.

set -o errexit
set -o xtrace

jlpm install
jlpm run registry &
jlpm run registry:init
jlpm run build
jupyter lab build || (jlpm run build:jupyter:remediate && jupyter lab build)
jupyter lab build
