#!/bin/bash
set -o errexit
set -o xtrace

cd jupyterlab
pip install -e .
jlpm run add:sibling ../dataregistry
jlpm run add:sibling ../dataregistry-extension
jlpm build:dev
jupyter lab build --dev
cd ../..